name: 'lintian'
author: 'Evgeni Golov'
description: 'Run lintian on a Debian package'
inputs:
  package:
    description: 'The package to run lintian on'
    default: '*.changes'
  options:
    description: 'Options to pass to lintian'
    default: '--info --display-info'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package }}
    - ${{ inputs.options }}
branding:
  icon: 'check-square'
  color: 'purple'
